# Generated by Django 4.1.7 on 2023-12-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
