# Generated by Django 4.1.7 on 2023-12-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_referral_clear_referral_is_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_img',
            field=models.ImageField(default='default.webp', upload_to='profile_images/'),
        ),
    ]
