# Generated by Django 4.1.7 on 2023-12-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermodel_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_img',
            field=models.ImageField(default='default.png', upload_to='profile_images/'),
        ),
    ]
